### ISSUE TITLE
Clarify information about branch, variable naming

### ISSUE THREAD

**Issue by Spring3** [dial-once/contributing-guidelines#8]
The Documentation needs to be updated to clarify how the branch can be named. Also, there must be a mention, telling that branch name does not depend on the label of the task this branch is meant to solve. So, in case the task has a label ```enhancement```, it should still be called as ```/feature/...```.
An update concerning variable naming would be also great

**Comment by mrister** [comment]
I did an update to dev guidelines to denote this but maybe more info can be added.

**Comment by Spring3** [comment]
@mrister Julien asked me to add this task. I think this information needs to be added here to a readme instead of the google drive word document as the last one is marked as deprecated.

**Comment by mrister** [comment]
ah ok, cool.

**Comment by Spring3** [comment]
Closing as new info was added
